### ISSUE TITLE
Set up Package Publishing 

### ISSUE THREAD

**Issue by jxnl** [instructor-ai/instructor-rb#4]

**Comment by sergiobayona** [comment]
I'm going to try to setup this "Publish Gem" Github action https://github.com/marketplace/actions/publish-to-rubygems as well as an action for automated test suite runs prior to publishing.

I'd need a GITHUB_TOKEN which I believe I can generate from the base Github repo and RUBYGEMS_API_KEY. Not sure if you want to keep ownership of the Rubgems account in which case you'd need to create the account. Then generate and provide the api key. Or if you prefer, I can generate one from my own Rubygems account.

**Comment by jxnl** [comment]
you can do it!

**Comment by jxnl** [comment]
also looks like instructor exists we'll need instructor-rb
